### ISSUE TITLE
Deleting value from session storage manually retains value in $sessionStorage.get

### ISSUE THREAD

**Issue by asadsahi** [gsklee/ngStorage#107]
I set a value in session storage using $sessionStorage.name. Then in the same browser session, I deleted the same session storage value by going in the developer tools window. However, $sessionStorage.name is still returning the value, unless I reload the page by hard refresh, at this point the value is not available. I expect that if the value is not in the session storage, then the ngStorage session storage service should not return the value.

Here is jsBin having same issue:
http://jsbin.com/vopehu/1/edit?html,js,output

Really confused. Please help.

**Comment by egilkh** [comment]
Good catch. I'll provide a pr tomorrow if I can.

**Comment by asadsahi** [comment]
Thanks @egilkh , I was planning to switch to another storage library, but like the simplicity of ngStorage. Will keep an eye on the updated. Thanks again.
