### ISSUE TITLE
Change prefix

### ISSUE THREAD

**Issue by furyscript** [gsklee/ngStorage#114]
I would like to change prefix of "ngStorage-" for key.

**Comment by egilkh** [comment]
https://github.com/gsklee/ngStorage/pull/76 is relevant.

Please file a PR with tests if you would like to contribute code.

**Comment by furyscript** [comment]
I don't have free time :(

**Comment by egilkh** [comment]
I'll look into it. I want to merge #76, but I feel it will need a little more work than just adding namespace. To do it correct it should be moved out into a provider scenario too, so you can set the prefix in the config phase of the app.

I'll look into it the coming days as I think this would be nice to have!

**Comment by furyscript** [comment]
I just wait for it, be quick though!!! :P
