### ISSUE TITLE
Undefined $localStorage value when set with native localStorage

### ISSUE THREAD

**Issue by Findiglay** [gsklee/ngStorage#115]
Hi,

I'm creating an app which sits behind a static homepage. Users log in through the homepage and their access token is stored with the native localStorage api before being redirected to the app.

My problem: once inside the angular app, I cannot access the token's value with $localStorage. I am always returned an undefined value. However, I can access the token within angular using the native localStorage method.

This makes me wonder, what are the benefits of using ngStorage over the native window storage api? Second, is it possible to retrieve values set with the native storage api using ngStorage?

I am attempting to use this inside httpProvider.interceptors:

     'request': function (config) {
        config.headers = config.headers || {};
        
        var token = $localStorage.token;
        console.log(token); // returns undefined

        // this works
        if (localStorage.token) {
          config.headers.Authorization = 'Bearer ' + localStorage.token;
        }
        return config;
      },

**Comment by egilkh** [comment]
Hey!

ngStorage prefixes it's values with `ngStorage-`, which is the reason you get undefined. 

As to what the benefits are it depends on what you use localStorage for. If you access localStorage once or twice in your application you don't need ngStorage. But if you have bigger collections or a lot of set/get operations it is quite nifty.
