### ISSUE TITLE
ngStorage error using karma.conf

### ISSUE THREAD

**Issue by jbarros35** [gsklee/ngStorage#117]
My karma cannot use my ngstorage:
Uncaught Error: Mismatched anonymous define() module: function (angular) {

karma.conf
 files: [
      'bower_components/angular/angular.js',
      'bower_components/angular-mocks/angular-mocks.js',
      'bower_components/angular-route/angular-route.js',
      'bower_components/angular-resource/angular-resource.js',
      'bower_components/ngstorage/ngStorage.js',
      'test-main.js',
      {pattern: 'lib/**/*.js', included: false},
      {pattern: 'src/**/*.js', included: false},
      {pattern: 'test/**/*.js', included: false}
    ],

**Comment by jbarros35** [comment]
Anyone? I tried using it and it always fails using with Karma configuration. Try it!

**Comment by egilkh** [comment]
I think included should be true unless you are using another loader?

On Monday, July 13, 2015, Jose Barros <notifications@github.com> wrote:

> Anyone? I tried using it and it always fails using with Karma
> configuration. Try it!
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/gsklee/ngStorage/issues/117#issuecomment-120955055>.
>


-- 
Egil Hanger
Heimdal IT AS
egil@heimdalit.no / 95737838

**Comment by egilkh** [comment]
If you check https://github.com/gsklee/ngStorage/blob/master/Gruntfile.js you can see the Karma config in use that does work for us and our tests.

**Comment by jbarros35** [comment]
Hi egilkh sorry but I cannot understand what you mean. My project is at github  https://github.com/jbarros35/node/tree/master/angulartemplate I cannot use it with ngstorage.

**Comment by egilkh** [comment]
I take it does work with your tests before you add ngStorage as a dependency ?

**Comment by jbarros35** [comment]
before add ngstorage was working fine. probably is related with some dependency, I don't know exactly. My modules work with ngstorage fine but I cannot test it.

**Comment by egilkh** [comment]
Could you try to provide requirejs with a config. I believe this is because ngStorage is considered ngstorage because of paths/folders.

This seems to work: 

```
    requirejs.config({
      baseUrl: 'bower_components',
      paths: {
        angular: 'angular/angular',
        ngStorage: 'ngstorage/ngStorage',
      }
    });

    requirejs(['ngStorage'], function (ngStorage) {
      console.log('hi');
    });
```

**Comment by jbarros35** [comment]
It failure before any attempt to load requirejs. I'm using karma.conf and running, my require js is not being loaded.

// Karma configuration
// Generated on Mon Jul 13 2015 09:49:28 GMT-0300 (Hora est. Sudamérica Pacífico)

module.exports = function(config) {
  config.set({

    // base path that will be used to resolve all patterns (eg. files, exclude)
    basePath: '',


    // frameworks to use
    // available frameworks: https://npmjs.org/browse/keyword/karma-adapter
    frameworks: ['jasmine', 'requirejs'],


    // list of files / patterns to load in the browser
    files: [
      'bower_components/angular/angular.js',
      'bower_components/angular-mocks/angular-mocks.js',
      'bower_components/angular-route/angular-route.js',
      //'bower_components/ngDialog/js/ngDialog.js',
      'bower_components/ngstorage/ngStorage.js',
      {pattern: 'javascripts/*.js', included: false},
      {pattern: 'test/**/*Spec.js', included: false},
      'test-main.js',
    ],


    // list of files to exclude
    exclude: [
      'javascripts/config.js'
    ],


    // preprocess matching files before serving them to the browser
    // available preprocessors: https://npmjs.org/browse/keyword/karma-preprocessor
    preprocessors: {
    },


    // test results reporter to use
    // possible values: 'dots', 'progress'
    // available reporters: https://npmjs.org/browse/keyword/karma-reporter
    reporters: ['progress'],


    // web server port
    port: 9876,


    // enable / disable colors in the output (reporters and logs)
    colors: true,


    // level of logging
    // possible values: config.LOG_DISABLE || config.LOG_ERROR || config.LOG_WARN || config.LOG_INFO || config.LOG_DEBUG
    logLevel: config.LOG_DEBUG,


    // enable / disable watching file and executing tests whenever any file changes
    autoWatch: true,


    // start these browsers
    // available browser launchers: https://npmjs.org/browse/keyword/karma-launcher
    browsers: ['PhantomJS'],


    // Continuous Integration mode
    // if true, Karma captures browsers, runs the tests and exits
    singleRun: false
  });
};

{
  "name": "y",
  "version": "0.0.0",
  "authors": [
    "Jose Carlos Barros <josecarlos.barros@gmail.com>"
  ],
  "license": "MIT",
  "dependencies": {
    "angular": "~1.2.28",
    "angular-route": "~1.2.28",
    "angular-mocks": "~1.2.28",
    "requirejs": "~2.1.19",
    "ngstorage": "~0.3.7",
    "chai": "~3.0.0",
    "ngDialog": "~0.4.0"
  },
  "resolutions": {
    "angular": "~1.3.x"
  }
}


sorry but tried everything, doesnt happen.

Error: Mismatched anonymous define() module: function (angular) {

**Comment by egilkh** [comment]
In your `bower_components` folder, could you try renaming ngstorage to ngStorage (not capitalization of S) ?

**Comment by jbarros35** [comment]
I tried, unfortunately not worked.
I have a very simple project with this configuration if you could try download it and run tests, if you install ngStorage it wont works anymore.

https://github.com/jbarros35/node/tree/master/angulartemplate

thank you for the assistance.

**Comment by egilkh** [comment]
Try
```
    // list of files / patterns to load in the browser
    files: [
      /*
      'bower_components/angular/angular.js',
      'bower_components/angular-mocks/angular-mocks.js',
      'bower_components/angular-route/angular-route.js',
      //'bower_components/ngstorage/ngStorage.js',*/
      {pattern: 'bower_components/**/*.js', included: false},
      {pattern: 'javascripts/*.js', included: false},
      {pattern: 'test/**/*Spec.js', included: false},
      'test-main.js',
    ],
```

in karma.conf.js. When using RequireJS you aren't supposed to include the path before tests are run as RequireJS will load them when needed (afaik). 

And add back ```ngStorage:'../bower_components/ngstorage/ngStorage',``` in test-main.js.

I have no problem running the tests after that with 'ngStorage' as a dependency, tested with adding 'ngStorage' in homeSpec.js define like ```define(['home', 'angularMocks', 'ngStorage'], function(app) {```

Could you give it a go?

**Comment by dgoncalves1** [comment]
Any solution to this? i'm starting a project with ngstorage and i need to user Karma

**Comment by egilkh** [comment]
Should be no problem. Just do the karma config correct :)

**Comment by dgoncalves1** [comment]
Thanks @egilkh

**Comment by jbarros35** [comment]
Hi egilkh thanks in fact the problem was in Karma.conf I was using wrong paths as you showed here.
Thanks for your assistance.
