### ISSUE TITLE
How to setItem?

### ISSUE THREAD

**Issue by LynnCo** [gsklee/ngStorage#122]
like:

localStorage.setItem('name', 'value')

It's not $storage.setItem, or $localStorage.setItem

**Comment by LynnCo** [comment]
Also when I have this setup

    # app.js
    var $storage = $scope.storage = $localStorage
    localStorage.setItem('name', 'value')

    # index.html
    {{ $storage.name }}

I can never get $storage.name to render. That is, I can't get the module working at a basic level

**Comment by btford** [comment]
Not super familiar with this module in particular. Looks like it should be bound to `{{ storage.name }}`.

One thing that might make it easier to debug together is to edit this plunker demo app with your code: http://plnkr.co/edit/9ZmkzRkYzS3iZkG8J5IK?p=preview

**Comment by tobiv** [comment]
The default/preferred way is demoed here: http://plnkr.co/edit/3vfRkvG7R9DgQxtWbGHz?p=preview
`$scope.$storage = $localStorage`
Instead of setting and getting, you directly add/manipulate properties on your $storage hook. The localStorage is updated automatically via watcher. Hope that helps.

**Comment by LynnCo** [comment]
I want to get and set though, specifically so I can avoid hardcoded form attribute names. 

So, like the situation in this demo http://plnkr.co/edit/9ZmkzRkYzS3iZkG8J5IK?p=preview where 'x' and 'y' are repeated several times. $localStorage.getItem('x') would avoid that :/

**Comment by tobiv** [comment]
var property = 'x';
    var get = $scope.$storage[property];
might do the trick?

Otherwise have a look at https://github.com/grevory/angular-local-storage, maybe that module better suits your needs.

**Comment by LynnCo** [comment]
yesssssss that's it that's what I want

**Comment by LynnCo** [comment]
dynamic set:
    for (var key in $scope.formdata) {
        $scope.storage[key] = $scope.formdata[key]

**Comment by LynnCo** [comment]
I'm talking as someone who just started writing Angular literally yesterday, but I am willing to bet that a dynamic set based on form data is common enough to go into the readme

**Comment by LynnCo** [comment]
Anyways, my problem is solved

**Comment by tobiv** [comment]
This is a javascript thing, see here: http://www.dev-archive.net/articles/js-dot-notation/

**Comment by LynnCo** [comment]
I figured as much, I started off tweeting about this with saying something like "I bet this is something obvious, like my not knowing javascript syntax"

**Comment by btford** [comment]
:+1: Thanks @tobiv for helping.

**Comment by LynnCo** [comment]
^_^

**Comment by egilkh** [comment]
``` javascript
app.controller('MahForm', ['$scope', '$localStorage', function ($scope, $localStorage) {
    $scope.formdata = $localStorage.formdata; 
});
```

Might be an "easier" way to use it without knowing the keys.
