### ISSUE TITLE
0.3.7 breaks in browserify land with angular that doesnt export itself

### ISSUE THREAD

**Issue by mkoryak** [gsklee/ngStorage#123]
0.3.7 will try to `require('angular')` but this is a problem because angular 1.3.x and earlier does not assign itself to `module.exports` so all you get back in an empty object. (this might be fixed in 1.4, I haven't looked) 

So I dont think you should require angular like that since it breaks browserified apps, i am using 0.3.6 which doesnt try to require it, and it works nicely.

**Comment by egilkh** [comment]
Hoy!

1.3.x breaks but it works in 1.3.6? 

I've added a check for unset/undef/null angular at line 17 (https://github.com/gsklee/ngStorage/blob/master/ngStorage.js#L17) but I haven't done a release yet. 

Would you be able to test using the master ngStorage.js file?

**Comment by mkoryak** [comment]
sorry, typo, your lib version 0.3.6 works, i am using angular 1.3.15 and it doesnt work there

**Comment by mkoryak** [comment]
that code you pointed out will not work because `angular` will be an empty object, so not falsey

**Comment by egilkh** [comment]
Aiight thanks. I'll have to look into this. RequireJS using 1.4 works, but I have not much experience with browswerify. I'll give it a spin! :)

**Comment by mkoryak** [comment]
Thanks for the quick response. Looking forward to your next version
