### ISSUE TITLE
Saving to storage and redirecting results in storage not being updated (zero $timeout doesn't help)

### ISSUE THREAD

**Issue by artemf** [gsklee/ngStorage#124]
I have 2 routes with different templates / controllers, I have this code in first controller:

```
    $scope.$storage = $localStorage;

    $scope.editVideoTemplate = function (videoTemplate) {
        $scope.$storage.videoTemplate = videoTemplate;
        $timeout(function() { $location.path('/editor'); });
    }
```

The first time editVideoTemplate is run videoTemplate gets saved in localStorage, but on consequent runs (selecting different videoTemplates) it fails to update the value in localStorage. So after initial save, EditorCtrl always gets initially saved videoTemplate from localStorage.

If I add 300ms timeout (instead of zero), it works as it should - videoTemplate gets saved and successfully retrieved every time.

Can we have direct setters / getters for these edge cases, when there's no point to force user to wait and force digest cycle?

**Comment by egilkh** [comment]
You could use the `$sync` function before doing the redirect.

**Comment by artemf** [comment]
@egilkh Unfortunately, it doesn't work:
```
    $scope.$storage = $localStorage;

    $scope.editVideoTemplate = function (videoTemplate) {
        $scope.$storage.videoTemplate = videoTemplate;
        $scope.$storage.sync();
        $timeout(function() { $location.path('/editor'); });
    }
```
And looking at the source code of $sync(), it looks like it just reads the contents from localStorage, not writes it back?

**Comment by egilkh** [comment]
Indeed. Too early and no coffee. My bad.

Maybe get/set should be added to enable this type of functionality. Or extend $sync with a write as well. 

I'm in the process of doing some refactoring to enable a few of the things discussed (in other issues or PRs) and I'll keep this in mind.

**Comment by artemf** [comment]
@egilkh Thanks! Having more control in these corner cases (like having explicit get/set) would definitely help!

**Comment by egilkh** [comment]
Use $apply() to force a write to the storage.

**Comment by hariom282538** [comment]
@egilkh @artemf  Please share code snippet.

**Comment by hariom282538** [comment]
`var setLocalStorage = function (token, uname)
    {
        $localStorage.token = token;
        $localStorage.name = uname;
        
    }

$timeout(setLocalStorage(token, userForm.uname), 500);

`
Module Used : ngStorage

**Comment by hariom282538** [comment]
```
var setLocalStorage = function (token, uname)
{
$localStorage.token = token;
$localStorage.name = uname;

}
$timeout(setLocalStorage(token, userForm.uname), 500);
```

> Module Used : ngStorage
