### ISSUE TITLE
LocalStorage in factories.

### ISSUE THREAD

**Issue by julesmoretti** [gsklee/ngStorage#125]
Hello there I am desperately trying to get local storage working in factories but so far with no success, perhaps because factories only can handle &rootScope rather then $scopes.

I have tried with both $rootScope.$storage and $localStorage. When being used with cordova the data gets added and is there until i close the app on the iPhone and reopen it, the data disappeared again. 

Any help would be most welcome. 

Thank you.

This is kind of an exemple of my factory:

```
angular
    .module('core')
    .factory('SharedData', [ '$rootScope', '$localStorage', function( $rootScope, $localStorage ) {

      if ( !$rootScope.$storage ) {
        $rootScope.$storage = $localStorage;
      }

            $rootScope.$storage.alumni = [];

            return {

                listAlumni: function() {
                  return  $rootScope.$storage.alumni;
                },

                findAlumn: function( id ) {

                  if ( id === undefined ) return false;

                    for (var i = 0; i <  $rootScope.$storage.alumni.length; i++) {
                      if ( $rootScope.$storage.alumni[i].id === id ) {
                        return  $rootScope.$storage.alumni[i];
                      }
                    };
                    return false;
                }
            };
    }]);
```

**Comment by egilkh** [comment]
Hi,
Any reason why you need to have the strorage on $rootScope?

I've used something similar to this code:

```
angular.module('core')
.factory('SharedData', ['$localStorage', function ($localStorage) {
  var alumni = $localStorage.alumni;
}]);
```

many times and it has worked well. Never did try to bind to $rootScope.

**Comment by egilkh** [comment]
Also, You reset the values in your array each time the SharedData factory is used by doing  `$rootScope.$storage.alumni = [];` I guess that is the error you are seeing.

**Comment by egilkh** [comment]
You can add a check like so to not have it reset between refresh / restarts:

```
if (!($rootScope.$storage.alumni instanceof Array)) {
  $rooScope.$storage.alumni = [];
}
```

**Comment by julesmoretti** [comment]
@egilkh - Thank you so much! What a silly mistake on my behalf. But I very much appreciate your time helping me with this.

Love ngStorage! Great work.
