### ISSUE TITLE
Keeping reference to localStorage key

### ISSUE THREAD

**Issue by steven10172** [gsklee/ngStorage#130]
Sometimes when writing applications it's easier to have a direct reference to the localStorage instead of having to keep track of the localStorage `key` (which makes calls longer in length). Currently with the way localStorage works and the way this library is written the only way to do that is with the following: 

```
var key = "counter"; // This key will change throughout the app
$scope.counter = $localStorage[key] || 42;

$scope.$watch('counter', function() {
    $localStorage.counter = $scope.counter;
});

$scope.$watch(function() {
    return angular.toJson($localStorage);
}, function() {
    $scope.counter = $localStorage.counter;
});
```

While that is due-able I believe there should be a way to have the localStorage wrapped in a `value` attribute to allow more of a direct route to it.

Example:
```
// Accessing the reference to the key
var key = "counter"; // This key will change throughout the app
$scope.counter = $localStorage[key];

// Using
{{counter.value}}
```

This will shorten calls from: `_$storage.$localStorage[_settings.currentSystem]` to `_currentSettings.value`

**Comment by egilkh** [comment]
Hi!

I'm confused. So I'm pretty sure I'm missing the point. Hope you'll excuse me.

You want a direct reference to 'localStorage'? That would be $window.localStorage. If you want the service provided by ngStorage that would be $localStorage. 

Do you want ngStorage to know when `key` has changed?

````
var key = 'counter';
$scope.counter = $localStorage[key];
// $scope.counter is not a reference to $localStorage.counter

key = 'ohNoes';
// $scope.counter should now be a reference to $localStorage.ohNoes
```

Is this the behaviour your would like?

**Comment by steven10172** [comment]
Sorry about the confusion. I'm confused myself after reading that. I'd like to be able to create a reference to a specific $localStorage key even though the object changes (due to serialization and deserialization) which is why `var myData = $localStorage.key;` doesn't receive changes.

To circumvent the new object creation with serialization and deserialization all values from localStorage can be stored in an attribute called `value`. Which would change access from `$localStorage.key` to `$localStorage.key.value`. But will allow the following:

```
var settings = $localStorage.key;
$scope.mySettings = settings;
settings.value = [1,2,3,4,5,6];
//$scope.mySettings,value will be updated to [1,2,3,4,5,6] due to not referencing the localStorage object directly
```

Example Plunkr that attempts to emulate localStorage the requested behavior: http://plnkr.co/edit/R57HoFng6R4JaEVKaNU2

**Comment by egilkh** [comment]
I do not want to make it so that we will have to use `.value` to get the values for a key.
