### ISSUE TITLE
TypeError: Converting circular structure to JSON  when trying to save BreezeJS object

### ISSUE THREAD

**Issue by rlahnum** [gsklee/ngStorage#131]
I am trying to save a BreezeJS object to session storage that by design has circular references.  Is there a way to override the serializer used?

**Comment by steven10172** [comment]
Use `.setSerializer` and `.setDeserializer` introduced with this commit 7df1d5333ff83d56a53e090608073bfc2cbc5ee0.

**Comment by egilkh** [comment]
Hey!

Sorry, haven't gotten around to releasing a version with that one yet, but if you can manage to use master those are indeed available during the config phase!

I also have to write the documentation. 

Thanks steven10172 for pointing it out!

**Comment by egilkh** [comment]
Closing this. As steven10172 pointed out that you can now change serializer :)
