### ISSUE TITLE
Uncaught Error: Mismatched anonymous define() module

### ISSUE THREAD

**Issue by james-daddies** [gsklee/ngStorage#132]
Trying to load ngStorage into my module and get a mismatched error. I am using requirejs so wondering if there is a different method I need use.

**Comment by egilkh** [comment]
Hoy!

You might need to specify ngStorage in you requirejs config. See https://github.com/gsklee/ngStorage/issues/117#issuecomment-121166318 it might have what you need?

**Comment by james-daddies** [comment]
Heh, should have read through the closed issues. The only issue I have is that when I learned angular it was via some funky requirejs setup. it made sense with how I was doing my application but I usually run into issues with modules because of this funky requirejs setup. I'm in too deep. lol.

Suffice to say that comment in #117 doesn't seem to translate to my application. I might look at a manually access to local storage.

**Comment by egilkh** [comment]
Hoy! Sorry I couldn't be of help. Let me know if you get stuck later and we'll give it another try if you want!

**Comment by james-daddies** [comment]
Okay, manual sucks...

**Comment by egilkh** [comment]
Hoy James!

Would you be able to try using the master ngStorage.min.js ? Just copy paste it down. I think this is fixed, sometimes requirejs does not pass the angular into the function.

**Comment by james-daddies** [comment]
that clears up that error. So getting it into my angular module...

My app is built up like like so

    define(
        ['app/run', 'app/config', '...'],
        function(run, config, ...) 
        {
            var app = angular.module('myApp', ['ngCordova', 'ui.router', '...'])
        }
    );

I added in `ngStorage` to my module array and then it blows up saying it failed to instantiate cause it can't find ngStorage.

**Comment by james-daddies** [comment]
Also notice a warning that angular is trying to be loaded twice.

**Comment by james-daddies** [comment]
Messing with things and didnt get anywhere. Reverted back and notice an error after the instantiate error states `Uncaught TypeError: Cannot read property 'module' of undefined`. Angular is not defined in ngStorage. Assume that is related to the angular is loading twice warning.

**Comment by egilkh** [comment]
Hey!

You'll need to have ngStorage in the define as well:
define(['app/run', ..., 'ngStorage'], function (...) {});

**Comment by egilkh** [comment]
Angular loaded twice might mean you have a script tag maybe for angular? You won't need that when using requirejs for dependencies.

**Comment by egilkh** [comment]
Hey @james-daddies did you get this working?

**Comment by james-daddies** [comment]
No, I ended up just using your module to build my own factories. That approach is working great.
