### ISSUE TITLE
$localStorage not setting value while redirecting 

### ISSUE THREAD

**Issue by binson143** [gsklee/ngStorage#135]
The given code is not working in Chrome and IE 10  

            securitysvc.validate($scope.loginModel).then(function (d) {
                var usertoken = d.data.auth_token;

              $localStorage.authtoken = usertoken;
              
                window.location = applicationUrl.clientUrl + "index.html";  // I am redirecting 
            } 

// If i remove the redirection  code  it will work, any idea ?

**Comment by egilkh** [comment]
It's because of digest cycles and timeouts. Please see https://github.com/gsklee/ngStorage/issues/124
