### ISSUE TITLE
Delete not work

### ISSUE THREAD

**Issue by furyscript** [gsklee/ngStorage#137]
I set prefix with localStorageProvider and I created some key.
delete $localStorage.key not work.

**Comment by egilkh** [comment]
http://plnkr.co/edit/qjTQa9AZyXqYAPnRUCgP?p=preview

Could you check if this example works for you?

**Comment by furyscript** [comment]
Your example works, but in my code not.
Have you update bower version?

**Comment by egilkh** [comment]
Hey, have not updated the version bower in a while no.

I'll do one when https://github.com/gsklee/ngStorage/pull/138 is merged (waiting to see if anyone in need of the functionality gives some feedback).

**Comment by furyscript** [comment]
I need update as fast you can...

**Comment by furyscript** [comment]
Also not work, I've made some test and not work!
test1:
$localStorage.set = 'Ylla';
alert($localStorage.set); --> OUTPUT: 'Ylla'
test2:
//$localStorage.set = 'Ylla';
alert($localStorage.set); --> OUTPUT: 'undefined' but in localstorage the value is present ('Ylla')

**Comment by egilkh** [comment]
I'm sorry furyscript. I'm not sure what you mean.

Could you provide a plnkr that fails? Would be a lot easier to see.

**Comment by furyscript** [comment]
If I put prefix, when reload page and I want to remove the key|value not work.
Also if I want to get value by key I got undefined.

**Comment by egilkh** [comment]
Thanks furyscript! I do indeed see a problem, let me get a fix done.

**Comment by egilkh** [comment]
Hi furyscript! 

http://plnkr.co/edit/mTeWc5CNkFDSDUIvcvgl?p=preview

I've changed this to use the ngStorage.js from the commit which should fix this issue. Would you be able to confirm?

**Comment by furyscript** [comment]
Thanks! Now it works fine :) update as soon as possible new version on Bower :)

I hope I was helpful!

**Comment by egilkh** [comment]
You were *very* helpful, thanks a lot for that.

I'll do a release for bower in some hours!

**Comment by furyscript** [comment]
Do you use a cache for this module?? If I delete a key from browser manually and I change state (so without reloading page) it returns always the value of key..

**Comment by ajinkyaw** [comment]
Guys. i do android development. according to the requirement, i want to open his home page ( developed in AngularJs) and do the google social login , in my android native app using webview component.
but when i click on google login button it shows me 
"This browser does not support Web Storage!" .. 
I reached to this issue page after searching a lot, 
Please help me if i am not in the wrong place, it would really save my job.
Thanks a lot guys.
