### ISSUE TITLE
Changing a property of an assigned object will update the values inside database

### ISSUE THREAD

**Issue by Sobiru** [gsklee/ngStorage#141]
First of all, I apologize for the confusing issue title. I didn't know how to explain it in a sentence.

I will try to provide a simple example to explain my issue: 

    $localStorage.TestObject = {};   // TestObject is initilized
    $localStorage.TestObject.testProperty = "hi";  // Setting a property of TestObject
    alert($localStorage.TestObject.testProperty); // Prints "hi" (correct)
    var localObject = $localStorage.TestObject;  // Assigning the ngStorage object to a local object
    localObject.testProperty = "bye"; // Changing the local object property to something else
    alert($localStorage.TestObject.testProperty); // Prints "bye" (correct?)

So as you can see changing the `localObject` property will update the value inside our ngStorage object. Is this behaviour okay?

If yes, then how can i assign a `$localStorage` object to something local and change its properties without overwriting the original `$localStorage` object?

**Comment by egilkh** [comment]
Hoy, yes both of those is how we enjoy using ngStorage.

For keeping a local copy I would suggest using `angular.copy`.

```javascript
$localStorage.TestObject = {};

var localObject = angular.copy($localStorage.TestObject);
```

**Comment by Sobiru** [comment]
Thank you @egilkh for the explanation, That was what i needed.
I'll close the issue.
