### ISSUE TITLE
Possible bug?

### ISSUE THREAD

**Issue by furyscript** [gsklee/ngStorage#148]
Hi,

When I store a key I see that it store like this
`"eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ1c2VySWQiOjEsImlhdCI6MTQzOTk4ODI3MX0.qkh74V2BJYozwnD8y__louOMJ0IcTqtSAvR19eQ3s9s"`

So if you print it in console with `localStorage.mykey` the result is
`""eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ1c2VySWQiOjEsImlhdCI6MTQzOTk4ODI3MX0.qkh74V2BJYozwnD8y__louOMJ0IcTqtSAvR19eQ3s9s""`

I don't want the extra apices on the string, I think it's bug because if you store with normal storage (`localStorage.test = "test"`) and you print it you got `"test"` and not `""test""`

**Comment by egilkh** [comment]
Hi,

This isn't a bug it's a result of ngStorage using angular.toJson/.fromJson to save objects to localStorage. 

localStorage only saves strings by default. But as we want complex objects in the store ({ a: b }) we need to serialize it down to a string in some way. Which is why.

**Comment by furyscript** [comment]
But this couse me an error with some plugin that they takes value with extra apices... How can I resolve it?

**Comment by egilkh** [comment]
Override the serializer / deserializer in ngStorage, note that this will only work if you only store string values with ngStorage.

You can probably do some other things to fix this as well.

**Comment by furyscript** [comment]
But you cannot store normal string/number (so not object, json...) without the apices?

**Comment by egilkh** [comment]
I does store numbers, strings and objects all the same by serializing it into a string.

**Comment by furyscript** [comment]
But I want in my localStorage normal values like `test` and not `"test"` :(

**Comment by egilkh** [comment]
I understand that. But what if you want to do something like `$localStorage.awesome = { a: 'object' };`

How would that be saved, because localStorage can not have objects...

If you ONLY use strings then you can use a serializer that is a simple as `function (a) {return a;}` or something and it will probably be okay. But if you use objects than you need to serialize it into localStorage.

**Comment by furyscript** [comment]
should you control typeof before storing it ...?

**Comment by egilkh** [comment]
We only serialize to/from JSON in ngStorage. Keeps it simple. But you could do typeof if you wanted in your own.

Example:
```javascript
angular.module('app', ['ngStorage'])
.config(['$localStorageProvider', 
  function ($localStorageProvider) {
    var mySerializer = function (value) {
      // Do what you want with the value.
      return value;
    };

    $localStorageProvider.setSerializer(mySerializer);
  }];)
```

**Comment by furyscript** [comment]
Yes I resolve using this
```javascript
    var mySerializer = function (value) {
        console.log(typeof value);
        if (typeof value === "string" || typeof value === "number") {
            return value;
        }
        // Do what you want with the value.
        return angular.toJson(value);
    };

    $localStorageProvider.setSerializer(mySerializer);
```

**Comment by egilkh** [comment]
Great! I'll close this then :)
