### ISSUE TITLE
Key Prefix Migration

### ISSUE THREAD

**Issue by SirDarquan** [gsklee/ngStorage#150]
Since we now have the ability to chose our own prefixes in v0.3.8, I decided I wanted to use it. What I noticed is that while the .get method of the provider prepends the keyPrefix to find the values in storage, the .set method doesn't. So when I went to migrate from the original key prefix of 'ngStorage-' to my own, I ended up naked keys. My code goes something like this:
```javascript
var prefs = $localStorageProvider.get("prefs"); //grabs the prefs key as 'ngStorage-prefs'
$localStorageProvider.set("prefs", null);   //this doesn't delete the item, which makes since over all
$localStorageProvider.setKeyPrefix("pfx-");
$localStorageProvider.set("prefs", prefs); // this set the prefs key as 'prefs' not 'pfx-prefs' as I expected
```
I suspect that the absence of the prefix on the set is a bug and wanted to bring it to your attention. What I'm really keen on is how will be able to remove keys in the provider? Can we also get a .delete  method since the delete keyword normally does that for us with the service?

**Comment by egilkh** [comment]
Thanks SirDarquan! Fixing.
