### ISSUE TITLE
IE11 completely broken, nothing stored in Localstorage

### ISSUE THREAD

**Issue by renege** [gsklee/ngStorage#162]
https://www.google.nl/webhp?sourceid=chrome-instant&ion=1&espv=2&ie=UTF-8#q=ie11%20windows%208.1%20local%20storage

Is there a workaround for this?

**Comment by gsklee** [comment]
Seems like an IE issue:
http://stackoverflow.com/a/21156133

If it's a browser problem then it's out of the scope of this library.
