### ISSUE TITLE
IE not storing/binding object containing values from input fields

### ISSUE THREAD

**Issue by rodrigosaling** [gsklee/ngStorage#167]
Here is the example http://plnkr.co/edit/nS9D4u0ReVc7nd3fG1uj?p=preview

It works fine on Chrome, but not on any IE.
You can change the input values and notice that `localStorage` object does not get updated. If you click on the button to reload the page, the original values are loaded.

Maybe it's related to https://github.com/gsklee/ngStorage/pull/47

Right now, the only solutions seems to not use objects as values and rename every property.

**Comment by egilkh** [comment]
Hey and thanks for the report. 

You you try this in a IE: http://plnkr.co/edit/Dl1c7F5wWtebxBytlCSI?p=preview ? I'm not able to spawn IE processes right now.

Just to see if it works.

**Comment by rodrigosaling** [comment]
Thanks for the replay @egilkh! But unfortunately the problem is still occurring on IE. When I reload the page, the input fields 3 to 6 load empty, even after entering text in them.

**Comment by rodrigosaling** [comment]
Just tested @dpogue 's fix (`(!$window.document.hasFocus || !$window.document.hasFocus()) && `) and it seems to make everything work in IE. But I don't yet know how to use it with Bower, Grunt, Git etc. I will take a look on that later.
