### ISSUE TITLE
Crash when webstorage is not supported

### ISSUE THREAD

**Issue by JulienBier** [gsklee/ngStorage#168]
Hi,
I found an issue when I try to save data in a browser with disabled local storage:

`undefined is not a function (evaluating 'webStorage.removeItem(storageKeyPrefix + k)')`

It can be solved adding **removeItem: angular.noop** at line 135
`var webStorage = isStorageSupported(storageType) || ($log.warn('This browser does not support Web Storage!'), {setItem: angular.noop, getItem: angular.noop, removeItem: angular.noop}),`

Thanks.

**Comment by egilkh** [comment]
Thanks for reporting this.

**Comment by JulienBier** [comment]
Thanks for the fix !
