### ISSUE TITLE
Changing the name of the key - localStorage

### ISSUE THREAD

**Issue by sebastiannm** [gsklee/ngStorage#17]
I'm trying to edit the key name on localStorage.
On the source code, I can see that the name is "ngStorage-", but I would like to add a variable to the keyname.

For example: ngStorageVAR-.

I tried change it but when I change the nameKey to something else I never get back the information stored on local, only when using the default it works

**Comment by MichielDeMey** [comment]
+1 for this issue

**Comment by stramel** [comment]
You can check out [stramel/ngStorage](https://github.com/stramel/ngStorage) that was @chicoxyzzy's library and is now deprecated but would probably hold you over until this issues is resolved.

**Comment by sompylasar** [comment]
Check out https://github.com/tymondesigns/angular-locker instead because
this repo is not maintained.

**Comment by egilkh** [comment]
Closing. Prefixing was introduced in https://github.com/gsklee/ngStorage/pull/126
