### ISSUE TITLE
 ngStorage.js:193     Uncaught TypeError: Cannot read property 'slice' of null

### ISSUE THREAD

**Issue by arv10singh** [gsklee/ngStorage#170]
* If ideal so much time (>5 minutes) then open another tab of any link in navbar then another tab is coming blank and previous tab in terminal that is exception throught.  

* Also if current browser (crome) ideal more then 5 minutes then refresh current tab also coming blank

 if (storageKeyPrefix === event.key.slice(0, prefixLength)) {
------------------------------------------------------------------------------------------
  $window.addEventListener && $window.addEventListener('storage', function(event) {
                  if (storageKeyPrefix === event.key.slice(0, prefixLength)) {
                        event.newValue ? $storage[event.key.slice(prefixLength)] = deserializer(event.newValue) : delete $storage[event.key.slice(prefixLength)];

                        _last$storage = angular.copy($storage);

                        $rootScope.$apply();
                    }
                });

**Comment by egilkh** [comment]
Should be fixed in https://github.com/gsklee/ngStorage/commit/d6daf6bd8305971fe056c0009eb542a5fb2eeff5
