### ISSUE TITLE
IE9 persistance issues on v0.3.9

### ISSUE THREAD

**Issue by kubosador** [gsklee/ngStorage#171]
Hi,

There are some troubles with IE9 and sessionStorage.
I know this is an old browser but we still have to maintain it due to legal matters.

I have not dug what's wrong, but there are no synchronisation between $sessionStorage and the current scope on version 0.3.9. When I falled back to 0.3.3, synchronisation worked again.

There might be a regression between those versions.

**Comment by rodrigosaling** [comment]
Hi @kubosador! I reported this issue already here https://github.com/gsklee/ngStorage/issues/167. That is better explained here https://github.com/gsklee/ngStorage/pull/47.
It seems that this solution https://github.com/gsklee/ngStorage/issues/167#issuecomment-142049099 makes the storage work again in IE9.
Around line 193 of ngStorage.js you can replace
`if (storageKeyPrefix === event.key.slice(0, prefixLength)) {`
with
`if ((!$window.document.hasFocus || !$window.document.hasFocus()) && storageKeyPrefix === event.key.slice(0, prefixLength)) {`

**Comment by kubosador** [comment]
Thanks for your quick answer. I'll test this solution in my next delivery.

**Comment by egilkh** [comment]
I'll get it in soon. But it seems some tests fail with this fix.
