### ISSUE TITLE
how to use $storage.pageA.X instead of $storage.X

### ISSUE THREAD

**Issue by surbhi92k** [gsklee/ngStorage#182]
My ng-model is $storage.pageA.X. How to work around with this? How to set default  values, delete and do everything else?

**Comment by egilkh** [comment]
Hi,

I usually use something like this

```
if (!$localStorage.Vars) {
  $localStorage.Vars = {
    default: 'values',
    X: 127,
  };
}

$scope.Vars = $localStorage.Vars;
```

`ng-model="Vars.X"`

Then ng-model should be able to use Vars.default or what have you. 

`delete $scope.Vars.X`
