### ISSUE TITLE
Release new version

### ISSUE THREAD

**Issue by omichelsen** [gsklee/ngStorage#186]
Hi, would it be possible to release a new version soon?

Specifically I'm looking forward to the fix from [this commit](https://github.com/gsklee/ngStorage/commit/c7367cf759da6c39ff4cbe6efe281c94fd70668c), which throws errors in all unsupported browsers, and in iOS private browsing.

Thanks.

**Comment by egilkh** [comment]
Hoy!

I won't have time today but I can do one tomorrow.

**Comment by omichelsen** [comment]
Thanks, would be great :+1:

**Comment by gillesdemey** [comment]
+1, waiting on this bug fix too :)

**Comment by bertyhell** [comment]
+1, Me too

**Comment by egilkh** [comment]
Done, bower and npm updated.

 A bit late, for that I apologize.
