### ISSUE TITLE
Unable to Work with JSON Array

### ISSUE THREAD

**Issue by siddmegadeth** [gsklee/ngStorage#189]
Canot get this below code to work. I am having large set of JSON which has to be added to localstrorage
var item = 
{
  "name: "someone",
 "age" : 23,
 "gender" : "male"

}
//Init
$scope.storage = $localStorage;
  $scope.storage.allSelectedTweets = [];

$scope.storage.allSelectedTweets.push(item);

On Page refresh all the values are gone.

**Comment by Midako** [comment]
try something like this

    var item = {
        "name: "someone",
        "age" : 23,
        "gender" : "male"
    }

    //Init
    $scope.storage = $localStorage;
    /* if allSelectedTweets doesn't exist or length is 0, initial a empty object and fill with item */
    if(!$scope.storage.allSelectedTweets || $scope.storage.allSelectedTweets.length === 0) {
        $scope.storage.allSelectedTweets = [];
        $scope.storage.allSelectedTweets.push(item);
    }

**Comment by egilkh** [comment]
Midako with the save!

👍
