### ISSUE TITLE
Add lz-string Compression

### ISSUE THREAD

**Issue by indolering** [gsklee/ngStorage#19]
The lz-string is a compression library built for localStorage.  It is **super** fast, geared towards the small values that are typically stored in localStorage, and only ~1.5KB when compressed.

**Comment by egilkh** [comment]
Closing this as master has ways to override serializer and deserializer now. Which should allow you to do this quite easy.

Re-open if anyone thinks this should be a default functionality.

**Comment by no-more** [comment]
Hi,

I think it would be great if it was a native feature (more optimized maybe). More and more apps need to store data offline, and the current browser limit is quite restrictive.

I will try to implement this feature with the serializer, and if it's working fine I will post it here.

Thanks.
