### ISSUE TITLE
Expose whether storage is supported or not, move test to configuration phase

### ISSUE THREAD

**Issue by OverZealous** [gsklee/ngStorage#190]
The result of `isStorageSupported` should be available on both the configuration and $storage object, so the user can be notified if it's disabled and will have adverse affects (ie: your login will not be saved across pages)

I also think that the test should happen above the `$get`, so the code won't throw errors if the `get` or `set` functions are used during the configuration phase.

Recommendation:

- Move `isStorageSupported` into the `_storageProvider` constructor, and store the results as `var `isSupported = this.supported = !!isStorageSupported(type);`
- Add `$storage.supported = isSupported`

I'd be willing to make a PR for this.

**Comment by egilkh** [comment]
Thanks for the feedback. I agree. 

Maybe $storage.supported should be a function (as not to get serialized into webStorage) ?

If you have time, please do make a PR :)

**Comment by OverZealous** [comment]
OK, I'll get a PR written.  I could also use `Object.define` to prevent serialization, but having it as a function is probably more consistent with the current API.

**Comment by gsklee** [comment]
Closed by #195.
