### ISSUE TITLE
'binding' $scope variables for persistence

### ISSUE THREAD

**Issue by francoisr** [gsklee/ngStorage#20]
Can it be simpler to store $scope variables?

From within a controller, I can assign the stored variable to a $scope variable like below:
        if (!$scope.$storage.detailsQueue) { $scope.$storage.detailsQueue = []; }
        $scope.detailsQueue = $scope.$storage.detailsQueue;
I could also use $default for initialization.
       $default( { detailsQueue : [] } )

Is there already a simple, single statement, syntax I missed?

If not, maybe something like :
       $storage.bind($scope,'varName',{defaultValue: 'randomValue123' ,storeName: 'customStoreKey'}); as found in https://github.com/agrublev/angularLocalStorage

The use case being to avoid editing existing code by declaratively providing immediate storage to existing variables.

Regards,

**Comment by egilkh** [comment]
Closing this as there is no follow up details.
