### ISSUE TITLE
prefix is not set correctly in sessionStorage

### ISSUE THREAD

**Issue by cicoub13** [gsklee/ngStorage#206]
I try to change prefix using setKeyPrefix. Everything is OK in localStorage (cicoub13-test = issue) but prefix is not set in sessionStorage (ngStorage-test = issue).

Config code : 
```javascript
$localStorageProvider.setKeyPrefix('cicoub13-');
```
Controller code :
```javascript
    $scope.testLocal = function() {
    	console.log('testLocal');
    	$localStorage.test = 'issue';
    };

     $scope.testSession = function() {
    	console.log('testSession');
    	$sessionStorage.test = 'issue';
    };
```

Test with yo angular and version 0.3.10 of ngStorage

![issue-ngstorage-prefix](https://cloud.githubusercontent.com/assets/1773153/13954746/6be49078-f042-11e5-906c-0df487f627c4.jpg)

**Comment by egilkh** [comment]
Okay. That is indeed strange. Will investigate.

**Comment by egilkh** [comment]
Wait.

You should need to do it for both $localStorageProvider and $sessionStorageProvider, as they are 2 different providers and services. 

Can you give it a try?

```
$localStorageProvider.setKeyPrefix('cicoub13-');
$sessionStorageProvider.setKeyPrefix('cicoub13-');
```

And see if that doesn't fix it for you?

**Comment by cicoub13** [comment]
It works for me, thanks for help. Maybe add examples for 2 providers in doc. Sorry for the issue.

**Comment by egilkh** [comment]
No need to be sorry! :)

Yes. I'll create an issue for adding explanation and examples in the readme.

**Comment by phongca22** [comment]
Please note them into Document.
