### ISSUE TITLE
npm publish version 0.3.7

### ISSUE THREAD

**Issue by Gregoirevda** [gsklee/ngStorage#209]
Could you please publish all your package versions. I'd like to help if possible, but sure have no access granted to publish

**Comment by Gregoirevda** [comment]
You have 2 npm versions: 
ng-storage: contains those versions  [ '0.3.0', '0.3.1', '0.3.2' ]
ngstorage : contains those versions  [ '0.3.3', '0.3.4', '0.3.5', '0.3.6', '0.3.8', '0.3.9', '0.3.10' ]

Could you please clone the 3 first package versions? And add A BIG NOTE on the ng-storage package

**Comment by gsklee** [comment]
@Gregoirevda `ng-storage` is not released by maintainers AFAIK; only `ngstorage` is official.

**Comment by Gregoirevda** [comment]
@gsklee Do you know the 2 npm packages points to this git repo which is called ngStorage?
So you have ng-storage and ngstorage npm packages, both points to the ngStorage repository. Crazy.
It's probably possible to add the first 3 packages to ngstorage and set a big note on what is what and why

**Comment by egilkh** [comment]
From the README: `NOTE: We are ngstorage and NOT ngStorage. The casing is important!`

0.3.7 var published in April.

```versions:
   [ '0.3.3',
     '0.3.4',
     '0.3.5',
     '0.3.6',
     '0.3.7',
     '0.3.8',
     '0.3.9',
     '0.3.10' ]
```
