### ISSUE TITLE
Safari 9.1 - QuotaExceededError when using sessionStorage in private browsing mode

### ISSUE THREAD

**Issue by OscarBarrett** [gsklee/ngStorage#210]
[The comment here](https://github.com/gsklee/ngStorage/blob/b41d73b744c9524784f44abad4c574377ba10acc/ngStorage.js#L36-L38) mentions that localStorage appears to be available in Safari's private browsing mode when it is not.

The same seems to apply for sessionStorage (`window['sessionStorage']` is defined) but it is not actually supported. `QuotaExceededError: DOM Exception 22` is thrown.

Note that Modernizr correctly reports it as false (`Modernizr.sessionstorage`).

**Comment by OscarBarrett** [comment]
#213

**Comment by gsklee** [comment]
Fixed by #213.
