### ISSUE TITLE
Is any way to decorate ngStorage service?

### ISSUE THREAD

**Issue by svit-ws** [gsklee/ngStorage#215]
I need for extending ngStorage with location dependent keys:
`    .decorator('$localStorage', function ($delegate, $location) {
        $delegate.gridState = function (state) {
            var key = 'grid-' + $location.url().slice(1);
            if (state) this[key] = state;
           return this[key];
        };
        return $delegate;
    })
`
but this creates also the "gridState" key in storage...

**Comment by egilkh** [comment]
If your only worry is getting .gridState in storage you can call it $gridState instead and ngStorage should ignore it on every $apply.

Ref: https://github.com/gsklee/ngStorage/blob/master/ngStorage.js#L177
