### ISSUE TITLE
$localStorage item returns undefined sometimes

### ISSUE THREAD

**Issue by miparnisari** [gsklee/ngStorage#219]
Gist here: https://gist.github.com/miparnisari/d4a457136140de3e1218d357b972da53. It's part of a router in a Cordova app.

Sometimes, the line that says `if($localStorage.profileCompleted){` returns an undefined value.

**Comment by egilkh** [comment]
Could you provide a complete but failing (sometimes) example to better understand and try to find the problem?

**Comment by miparnisari** [comment]
It was a bug in my app, sorry!
