### ISSUE TITLE
Problem with bower

### ISSUE THREAD

**Issue by nicearma** [gsklee/ngStorage#223]
I don't know if you can change the ref at Bower, but with the last commit something is not working with bower 

> bower ENORESTARGET  No tag found that was able to satisfy 0.3.10
> 
> Additional error details:
> Available versions in https://github.com/agrublev/ngStorage.git: 0.3.2, 0.3.0, 0.2.0, 0.1.8, 0.1.7, 0.1.6, 0.1.5

**Comment by egilkh** [comment]
Hey there!

As stated in the readme: `NOTE: We are ngstorage and NOT ngStorage. The casing is important!`

Should work if you use `ngstorage` instead of `ngStorage`.
