### ISSUE TITLE
Unexpected token e in JSON

### ISSUE THREAD

**Issue by darrais** [gsklee/ngStorage#224]
I have used the following to change the prefix value used by ngStorage:
`
$localStorageProvider.setKeyPrefix('wikitime_');
$sessionStorageProvider.setKeyPrefix('wikitime_');
`

However, by doing so, I get the following error:
`angular.js:13642 SyntaxError: Unexpected token e in JSON at position 0`

Have any idea why this happens and how can I fix it?

**Comment by egilkh** [comment]
Hey there.

Could you provide and example that fails? Or does it always fail when you use those prefixes?

**Comment by darrais** [comment]
Hey!

I think I understood now why this was happening. I had another key with the same prefix that was not serialized. The value of this key started exactly with the letter `e`.
