### ISSUE TITLE
Get all keys stored

### ISSUE THREAD

**Issue by furyscript** [gsklee/ngStorage#225]
How can I get all stored keys in localstorage?
If there isn't this feature can be implemented??

**Comment by egilkh** [comment]
Maybe `Object.keys($localStorage)` can help you? :)

Note that `Object.keys` will also give you $reset and $default (functions on the $localStorage object). Which you'll have to filter out if you do not want them.

Alternative $window.localStorage provides access to Storage item.

**Comment by furyscript** [comment]
Sure I forgot that `$localStorage` is an object :( thank you!
