### ISSUE TITLE
Change Prefix after configuration

### ISSUE THREAD

**Issue by fniwes** [gsklee/ngStorage#227]
At configuration time I  don't know what prefix to use, because it will be asked to the user. (I want to use the prefix to have different storages for different users).

But I don't know how to inject the provider in a controller, or another service.
Neither how to change the prefix outside config.

Is it possible?

**Comment by RoelRoel** [comment]
I also need a prefix based on the logged in user. So some preferences can be stored per account. I want to set the prefix after login occured. Is this possible?

**Comment by egilkh** [comment]
Ahoy!

Neither of those are possible as it stands now. But you could prefix the key of the objects that you put into the storage.

var userPreferences = $localStorage.userPreferences['userName'] || {}; 

As a bad example :)
