### ISSUE TITLE
memory leak in ngstorage (while running jasmine)

### ISSUE THREAD

**Issue by JanEggers** [gsklee/ngStorage#245]
hi i have a close eye on memory and currently i have found a memory leak related to ngstorage.

ngstorage keeps my rootscopes alive while unittesting.

![image](https://cloud.githubusercontent.com/assets/6747376/18922434/e50409e2-85a8-11e6-9101-5a6d25d639e6.png)

should not be relevant for live apps but is there a way to fix that?

**Comment by nc-babelv** [comment]
Are you using [ngMock](https://docs.angularjs.org/api/ngMock)? We dealt with this issue in our tests by mocking `$localStorage` and `$sessionStorage`.
```js
  module('ngStorage', ($provide) => {
    function mockStorage() {
      this.$apply = this.$default = this.$reset = this.$supported = this.$sync = () => {};
    }

    $provide.service('$sessionStorage', mockStorage);
    $provide.service('$localStorage', mockStorage);
  });
```
We're using jasmine and put that in a global `beforeEach`.  Depending on your usage you may need to flesh the mocked functions out more.

**Comment by saskodh** [comment]
I also stumbled on this issue. These two event handlers should be unregistered on `$rootScope.$on('$destroy')`.
```javascript
$window.addEventListener('storage', function(event) {
    // ...
});

$window.addEventListener('beforeunload', function() {
    // ...
});
```
