### ISSUE TITLE
Checking if the browser supports localStorage should try to set and get data

### ISSUE THREAD

**Issue by kennethlynne** [gsklee/ngStorage#36]
If localStorage is disabled (in safari) or max-size is set to 0, it will still report window.localStorage as available, but crash when trying to write to it.

Easily solved by doing a try/catch and trying to write and read.

**Comment by sinxwal** [comment]
+1

**Comment by egilkh** [comment]
This should be solved.

**Comment by rubinovitz** [comment]
This is still erroring after a hard refresh in safari private.

**Comment by egilkh** [comment]
@rubinovitz Could you create a new issue? Preferably with a small example and error message. And we'll have it sorted out :)

**Comment by madssj** [comment]
For anyone else looking at this issue, it is not present in `0.3.10` as far as I can tell.
