### ISSUE TITLE
How to wait on delete to take place

### ISSUE THREAD

**Issue by ronnieoverby** [gsklee/ngStorage#39]
In my app, when a user logs out I want to 
1. Delete their auth token from $localStorage.
2. Reload the page

I noticed that this code wasn't working:

``` javascript
delete $localStorage.authToken;
$window.location.href = '/';
```

When the page reloads, the auth token is still present.

So, as an experiment I put the reload in a timeout and it worked.

``` javascript
delete $localStorage.authToken;
$timeout(function () {
    $window.location.href = '/';
}, 110);
```

I also noticed that the timeout had to be greater than 100... which leads me to believe that this has something to do with _debounce section in your code, which I don't quite understand, yet.

What's the best way that I can be sure that the data has been removed from web storage before reloading the page?

**Comment by ckahle33** [comment]
The `$timeout` works, but I agree that it's ugly. Anyone using a better solution?

**Comment by fenos** [comment]
Please someone has found a solution for this that is not the $timeout? I'm having few redirect loops for it with in the same your scenario

**Comment by lordnox** [comment]
I did introduce a solution in my fork https://github.com/raynode/ngStorage

As gsklee seems not to be available I'd propose you to use that repository?

The workaround is something like:

```
$localStorage.test = 123
// not saved yet, would debounce for 100ms
$localStorage.$save();
// now it was saved immediately
```

**Comment by fenos** [comment]
Thank you, I absolutely use your repo, but the issue is not saving the data on the storage, but deleting it.

for example this is what i currently use:

~~~
//Handle token expiration
            if (response.status === 403 && response.data.context === 'auth-token') {

                $localStorage.$reset();

                delete $http.defaults.headers.common['Authorization'];

                // if i redirect straight away without the timeout it get in a loop because 
                // i guess it take same time to delete data from the storage
                $timeout(function() {
                    $window.location.href = '/auth/login';
                    $window.location.reload();
                },110);

                return false;
            }
~~~

**Comment by lordnox** [comment]
Have you tried this:

```
//Handle token expiration
            if (response.status === 403 && response.data.context === 'auth-token') {

                $localStorage.$reset();

                delete $http.defaults.headers.common['Authorization'];

                // tell the system to save immediately
                $localStorage.$save();

                // no need for $timeout
                $window.location.href = '/auth/login';
                $window.location.reload();

                return false;
            }
```

**Comment by lordnox** [comment]
And I finally need to add my rep to bower as `ng-storage`...

**Comment by fenos** [comment]
Yes it does work! :+1:  Thanks so much, I had to add few $localStorage.$save() method when saving the data on the storage it seem not adding it automatically as before, but It took me 20 seconds so no problem! Great fix

**Comment by sompylasar** [comment]
@egilkh is now maintaining this repo.

**Comment by egilkh** [comment]
Probably try $location to do the redirect to let digest and such instead of
$window?

On Thursday, June 11, 2015, John Babak <notifications@github.com> wrote:

> @egilkh <https://github.com/egilkh> is now maintaining this repo.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/gsklee/ngStorage/issues/39#issuecomment-111199893>.
>


-- 
Egil Hanger
Heimdal IT AS
egil@heimdalit.no / 95737838
