### ISSUE TITLE
$scope.$storage = $localstorage puts everything inside current scope in storage

### ISSUE THREAD

**Issue by Nichiatu** [gsklee/ngStorage#42]
Weird bug?

This is the code I'm using:

    $scope.organisation = {
        id: 0
    };

    $scope.updateOrganisation = function (organisation) {
        console.log(organisation);
    }

    $scope.load = function (adUsername) {

        $scope.$storage = $localStorage;
        // function logic
    }

And for some weird reason it's placing everything within my $scope inside my local storage. Any info on this?

**Comment by moto0000** [comment]
Just chenge this line:
```
$scope.$storage = $localStorage;
```
to:
```
$scope.$storage = angular.copy($localStorage);
```
