### ISSUE TITLE
Add warning for 'bower install ngStorage' in readme.md

### ISSUE THREAD

**Issue by ovidiubuligan** [gsklee/ngStorage#44]
I installed ngStorage via bower and it seams that ngStorage bower comonent was https://github.com/agrublev/angularLocalStorage in fact.

Around the 'bower install ngstorage' command description in *readme.md* there should be a warning about the other 'ngStorage' with cappital 'S'

**Comment by egilkh** [comment]
https://github.com/gsklee/ngStorage/commit/9d0827882ca7139ea34cce581a9382a939694ff6
