### ISSUE TITLE
Comparison with AngularStorage and Angular-localForage?

### ISSUE THREAD

**Issue by webmaven** [gsklee/ngStorage#45]
I'd appreciate a bit of documentation added to the README that compare these very similar solutions that overlap in functionality, especially the 'sweet spot' use case each addresses.

**Comment by egilkh** [comment]
Closing as I'm a sucker for cleanup. 

Please open new issue/pr if anyone wants :)

**Comment by webmaven** [comment]
@egilkh
> Please open new issue/pr if anyone wants :)

Since you insist, I opened #106.
