### ISSUE TITLE
$reset does not remove items from webStorage

### ISSUE THREAD

**Issue by rortegax2** [gsklee/ngStorage#48]
I just recently tried this ngmodule and found that when I reset the storage when I try to access the $sessionStorage it reloads the data, because it is still there... I patched it locally to make it work in this way:

<blockquote>
         $reset: function(items) {
                            for (var k in $storage) {
                                '$' === k[0] || (delete $storage[k] && webStorage.removeItem('ngStorage-' + k));
                            }

                            return $storage.$default(items);
                        }
</blockquote>
Hope this helps.

**Comment by rriemann** [comment]
:+1:

**Comment by timotheemoulin** [comment]
Hi,
I also have this issue. Could you please accept @rortegax2 pull request?

Thanks

**Comment by jloveland** [comment]
please merge this PR
