### ISSUE TITLE
Issues on Windows Phone (Mobile IE 9&10)

### ISSUE THREAD

**Issue by slane** [gsklee/ngStorage#49]
For some reason, this module fails on Windows Phone -platforms. The module does not persist data to web storage properly. The origin of the issue is on line 77:
```
delete _last$storage[k];
```
For some reason, this does not properly delete the keys from the `_last$storage`-object. Only the last delete operation of the forEach-loop persists and this causes the next for loop (`for (var k in _last$storage) {...}`) to remove everything except the last item from web storage.

**Comment by jlkalberer** [comment]
I think I have a solution in this pull request. https://github.com/gsklee/ngStorage/pull/78

**Comment by egilkh** [comment]
As #78 is merged I'll close this. 

Please create/reopen if problem continues with the fix from #78.
