### ISSUE TITLE
Reserve $ for Angular properties and services

### ISSUE THREAD

**Issue by IlSocio** [gsklee/ngStorage#55]
Hi, first of all, let me say that I'm new to AngularJS.
I just came across this module and I'm a bit confused... because according the official style guide: http://google-styleguide.googlecode.com/svn/trunk/angularjs-google-style.html
To do the things in the "Angular way", we should avoid using $ for all our services... 
So, it wouldn't be better to rename the $localStorage and $sessionStorage to localStorage and sessionStorage?

**Comment by egilkh** [comment]
Closing this. Some valid points here and please do re-open if you feel strongly about this.

The link provided by requester is a style guide for people at Google writing Angular code. And they seem to have forgotten about it as angular-material uses $ to prefix it's services. 

I think we'll let this be until someone wants to fight for the change again :)
