### ISSUE TITLE
Dates get squashed into strings, consider customer serializer support?

### ISSUE THREAD

**Issue by kbaltrinic** [gsklee/ngStorage#67]
Adding a date to either $localStorage or $sessionStorage results in the date eventually becoming a string at some point (i.e. when the app reloads).  This is of course because when the date is added, it gets serialized to a string, but remains a date in $localStorage/$sessionStorage until something happens (browser reload) to cause the object to be reloaded from storage, then suddenly what was a date is now a string.

This is arguably something of a "known issue" since this is the behavior of the underlying toJson/fromJson methods.  However since ngStorage goes to the trouble of hiding the true string nature of the storage from the developer (thank you), the behavior is in effect a leaky abstraction.  Moreover, accounting for this behavior in code is messy.

Arguably other things also do not serialize and deserialize symmetrically either.  (regular expression or most any other object that is not just a hash map).  Therefore implementing a hard coded fix for dates may be a slippery slope, not to mention breaking backward compatibility.

However, it would be possible to introduce the ability to inject customer serialization/deserialization functions into the services at configuration time.  What are your thoughts on such a feature?

**Comment by kbaltrinic** [comment]
I am re-opening this issue because I have an entirely new use-case for custom serialization that @sompylasar 's solution does not address.  Specifically I have some objects that are very large being stored and basically I only want parts of the object to be stored because there are some parts that if I loose, I can just recreate them from the back-end data.  In short, I need to be able to mark some areas of the object as "do-not-serialize".  But this only applies when they are being serialized into local storage (or session storage).  I do need to be able to post the entire object via $http.

I can see other use cases for this as well.  Custom handling of circular references or situations where the same instance of an object exists in more than one place in the object graph. (default deserialization causes these to become two separate objects).

**Comment by egilkh** [comment]
This could be solved if we refactor out serialization (today using angular.to/.from) into it's own service we inject. And provide a method of changing this, maybe in the config phase? 

Meaning the user would need to provide it's own serializer/deserializer service that ngStorage would inject and use. Does a little overhead in initialisation.

**Comment by litchfield** [comment]
+1

**Comment by kbaltrinic** [comment]
@egilkh, yes this is what I had in mind.  I was thinking that in the config phase there should be a way to provide a custom serialization and deserialization function for each of the two services, $sessionStorage and $localStorage with the defaults being the angular.to/from JSON implementations.  If I understand your thoughts, wrapping the angular.to/from into a service that gets injected makes sense.  Then we could effect what we want by decorating the serialization service.

**Comment by egilkh** [comment]
Closing. This should be in place.
