### ISSUE TITLE
Project is completely unmaintained?

### ISSUE THREAD

**Issue by magwo** [gsklee/ngStorage#72]
Last commit about a year ago.
Does there exist a good fork for this project?

**Comment by martinmcwhorter** [comment]
Use this fork: https://github.com/sompylasar/ngStorage.git

**Comment by sompylasar** [comment]
@martinmcwhorter I'm not currently maintaining it, so I would recommend https://github.com/tymondesigns/angular-locker instead.

**Comment by ecaron** [comment]
My team is switching to https://github.com/grevory/angular-local-storage/

**Comment by iltera** [comment]
:+1: for grevory's angular local storage project.

**Comment by rllola** [comment]
:+1:

**Comment by egilkh** [comment]
Hi,

I'll be your new maintainer.
