### ISSUE TITLE
firefox trouble and localStorage

### ISSUE THREAD

**Issue by kotmatpockuh** [gsklee/ngStorage#74]
all is describen here: http://stackoverflow.com/questions/28136231/angularjs-controller-is-caching-in-firefox-and-ie-how-to-disable

in ie and firefox - something is bad with localStorage

**Comment by egilkh** [comment]
Closing as demo is not enough to demo problem and poster doesn't want to provide demo over at link provided. Please do re-open if you are still having this issue.
