### ISSUE TITLE
Access is denied in IE9/11 - webStorage line 79 ngStorage.js

### ISSUE THREAD

**Issue by tommyjepsen** [gsklee/ngStorage#75]
Getting an error in IE9 and 11 with Access is denied. Its not on all machines, and so first thought was security settings. 

IE debugged and said that  line 79 in ngStorage.js webStorage.removeItem('ngStorage' + k); it expected a function.

What does it mean?

**Comment by sompylasar** [comment]
This repo is not maintained. Please switch to the more maintained alternative: https://github.com/tymondesigns/angular-locker

**Comment by bmulholland** [comment]
We're encountering this as well. Contrary to the message above, this repo DOES appear to be maintained.

The error we're seeing is:
`SCRIPT5: Access is denied`
At `$window[storageType]` of `var webStorage = $window[storageType] || ($log.warn('This browser does not support Web Storage!'), {})`

**Comment by egilkh** [comment]
Fixed in https://github.com/gsklee/ngStorage/pull/103
