### ISSUE TITLE
Bug when storing complex objects on mobile devices (cordova, iOS)

### ISSUE THREAD

**Issue by stefanmdt** [gsklee/ngStorage#80]
This bug has cost me days of investigation. When storing complex objects, the objects can be accessed while app is running but on reload they are lost. I switched to angular-locker, changed nothing else in my code than getters/setters and it works like a charm ...

**Comment by phaq01** [comment]
I've got the same behaviour with chrome.

**Comment by egilkh** [comment]
I have tried a lot to reproduce this but I just can not. Can you provide a bit more information to help in finding it? 

I did have a problem using it with cordova on a Nexus 5 and 7 because of a bug in the browser. But not a bug with the library.
