### ISSUE TITLE
Looking for Maintainers

### ISSUE THREAD

**Issue by gsklee** [gsklee/ngStorage#84]
Hi everyone, sorry for the dead silence for quite a long time.

To put it short, I've moved away from the Angular ecosphere and am not very likely to invest any more substantial amount of time into this project, so I've decided to open it up for those who actively use it in their daily developments.

I've got no prior experience on this so I'm not sure if turning this repo into an organization is good or bad, so please weigh in and share your thoughts on the pros and cons of establishing an organization to oversee this project.

Also if you're interested in helping to maintain and shape the future of ngStorage, you're more than welcome to give a shout below and let us know how you'd like to help.

cc @egilkh @raynode @sompylasar @AyogoHealth @scalablepress @halkon and thanks for your past contributions!

**Comment by gsklee** [comment]
Also @revolunet

**Comment by revolunet** [comment]
thanks, same move here :)

**Comment by gsklee** [comment]
@revolunet The fact that I cannot reuse this piece of code in my new React apps implies something fundamentally wrong about these framework lock-in modules. I've got something in mind about a framework agnostic localstorage solution that maybe I'll find some time to implement some day...

**Comment by egilkh** [comment]
I still use this module for small apps (some in production) and experiments. If no one else wants to maintain it I'll step up.

I don't think you need to create a new organisation for this one repo. But I'll leave that up to you. However you think is the best for you to be honest.

**Comment by gsklee** [comment]
@egilkh Yeah, I guess we don't have that much people here to mandate an organization... I'll give you access to the repo now so you can see if you'd like to merge your fork back and make adjustments as you like etc.

**Comment by rebelholic** [comment]
@gsklee I can help you to maintain this repo maybe with my friend because we have some projects need help from this repo. Also what's your email? I want contact you via email.

**Comment by egilkh** [comment]
@rebelholic Any help will be appreciated. My mail is egilkh@gmail.com.

First order of business (so to speak) will be to merge my fork and get that released (the fork contains pull requests and some minor improvements). And up after that is starting to go through the issues and pull requests.

**Comment by gsklee** [comment]
@egilkh Just FYI it seems the name [`ngstorage`](https://www.npmjs.com/package/ngstorage) on npm is still available, so maybe you'd wanna do a `npm publish` to claim it.

**Comment by rebelholic** [comment]
@egilkh I already sent my email (m4rx.only@gmail.com) for you. If I have a free time I can help to shape and fix some bugs from this plugin

**Comment by egilkh** [comment]
@gsklee I've published it there.

**Comment by gsklee** [comment]
@egilkh Thanks :+1:

**Comment by rainboxx** [comment]
Glad to see that in almost no time someone else took over :-). If you still need some hands I'd be willing to help.

**Comment by RajeshHegde** [comment]
Looks interesting. I'm in if you are still looking.

**Comment by ohjames** [comment]
Thanks to those who offered to take over maintenance and thanks to @gsklee for passing on the project instead of letting it die!

**Comment by gsklee** [comment]
Major credit should go to @egilkh for keeping up a well maintained fork over the years so things are moving smoothly once more :100:

**Comment by shali3** [comment]
@egilkh you might want to remove the "Looking for maintainers" message from the main README.
It looks like this library will not be maintained soon. Kind of a turn-off 😉
