### ISSUE TITLE
Custom parsers

### ISSUE THREAD

**Issue by litchfield** [gsklee/ngStorage#86]
Some variables need to be re-instantiated on load. 

We should be able to specify parser function(s) to do this.

Also, $sessionStorage should be instantiated so it can contain options and values specific to the target scope's usage.

Example solution --

    $scope.$storage = $sessionStorage({
    	parseFromStorage: {
    		myobject: function(value) {
    			return new FunkyObject(value);
    		}
    	},
    	defaults: {
    		myobject: new FunkyObject();
    	}
    });

**Comment by egilkh** [comment]
We have a conversation on this over at https://github.com/gsklee/ngStorage/issues/67

I'll close this one in favor of that.
