### ISSUE TITLE
Adding Encryption

### ISSUE THREAD

**Issue by tazzytazzy** [gsklee/ngStorage#94]
Ever thought about adding an encryption layer to this?
Example at: http://codepen.io/nekman/pen/xhwgs

Example encryption service that uses localstorage: https://dl.dropboxusercontent.com/u/705811/encryptedlocalstorage.js

Could be an optional usage.

**Comment by egilkh** [comment]
I think it would be better to keep the crypto outside the core module.

Once we get (working on it :) ) a way of providing custom (de)serialization this should be easy to have.

**Comment by egilkh** [comment]
Close as you can do this by providing serializer/deserializer now.
