### ISSUE TITLE
NPM compile-time dependencies included in production section

### ISSUE THREAD

**Issue by Tzrlk** [gsklee/ngStorage#96]
The current version of ng-storage on npm is unusable, because it pulls down grunt, karma, etc in its production dependencies. Because there is some kind of peer dependency issue, this causes all subsequent npm install operations to fail. Grunt, Karma, etc. should only be included in the development scope and be completely unnecessary during production use.

**Comment by Tzrlk** [comment]
Looking at the latest release code, this problem only appears to exist because 0.3.4 has not been published to NPM. Can this be done?

**Comment by paulstatezny** [comment]
Also experiencing this. Thanks!

**Comment by egilkh** [comment]
The correct one to use is ngstorage.

https://www.npmjs.com/package/ngstorage
