### ISSUE TITLE
Local storage not saving when unit testing

### ISSUE THREAD

**Issue by bingecoder** [gsklee/ngStorage#97]
I'm assigning various values to local storage in our Jasmine unit tests like so:

beforeEach(inject(function ($controller, $injector, $rootScope) {

  $localStorage = $injector.get('$localStorage');
  $localStorage.webAPIUrl = 'myUrl';

}

it('Can make API call', function() {
      
  var apiCall = $localStorage.webAPIUrl + params;
  httpBackend.expectGET(apiCall).respond({});

});

Unfortunately, anything I set in $localStorage is undefined when I try to retrieve it in the application, so tests like this fail because the angular service in the application utilizes $localStorage.webAPIUrl.  These tests were fine previously (when we just stored values like this in window.AppConfig), but now we're running into this problem after switching to ngStorage.

Is there a piece of the puzzle I'm missing, or is there a problem with ngStorage and unit testing?

**Comment by egilkh** [comment]
Since it depends on $timeout service you might need to add `$timeout.flush();` to wait for the timeout service to complete it's tasks before checking.

**Comment by bingecoder** [comment]
I finally seem to have it working--looks like it was an issue specific to our application rather than an issue with ngStorage.  Thank you for your suggestion, however.
